apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-pod
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: busybox
          command: ["sh", "-c", "while true; do echo Hello from worker; sleep 10; done"]
